ReksadanaRekon/Controllers/Transactions/RedempsController.cs
using Dapper;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using ReksadanaRekon.Models;
using ReksadanaRekon.Models.Data;
using ReksadanaRekon.Models.Master;
using ReksadanaRekon.ViewModels;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data.SqlClient;
using System.Globalization;
using System.Linq;
using System.Net;
using System.Runtime.InteropServices;
using System.Web;
using System.Web.Mvc;
using _excel = Microsoft.Office.Interop.Excel;

namespace ReksadanaRekon.Controllers.Transactions
{
    public class RedempsController : Controller
    {
        ApplicationDbContext _context = new ApplicationDbContext();
        SqlConnection _con = new SqlConnection(ConfigurationManager.ConnectionStrings["ReksadanaRekon"].ToString());

        // GET: Reds
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public ActionResult UploadFiles(HttpPostedFileBase[] files)
        {
            if (User.Identity.IsAuthenticated)
            {
                var manager = new UserManager<ApplicationUser>(new UserStore<ApplicationUser>(new ApplicationDbContext()));
                var currentUser = manager.FindById(User.Identity.GetUserId());

                var resultupload = new List<ResultUpload>();
                if (ModelState.IsValid)
                {
                    #region Upload
                    foreach (HttpPostedFileBase file in files)
                    {
                        if (file != null)
                        {
                            if (file.FileName.EndsWith("xlsx") || file.FileName.EndsWith("xls") || file.FileName.EndsWith("csv"))
                            {
                                #region Init
                                _excel.Application application = new _excel.Application(); ;
                                _excel.Workbooks workbooks = application.Workbooks;
                                _excel.Workbook workbook = null;
                                _excel.Worksheet worksheet = null;
                                _excel.Range range_ = null;
                                string path = path = Server.MapPath("~/Content/Files/" + file.FileName);

                                //try
                                //{
                                file.SaveAs(path);

                                workbook = workbooks.Open(path);
                                worksheet = workbook.ActiveSheet;
                                range_ = worksheet.UsedRange;

                                string judul = ((_excel.Range)range_.Cells[1, 1]).Text;
                                string judul2 = ((_excel.Range)range_.Cells[1, 2]).Text;
                                string judul3 = ((_excel.Range)range_.Cells[1, 3]).Text;
                                string judul4 = ((_excel.Range)range_.Cells[8, 1]).Text;
                                string judul5 = ((_excel.Range)range_.Cells[8, 2]).Text;
                                judul = judul.ToLower().Replace(" ", "").Replace("\"", "").Replace("\\", "").Replace(",", "");
                                judul2 = judul2.Replace(" ", "").ToLower();
                                judul3 = judul3.Replace(" ", "").ToLower();
                                judul4 = judul4.Replace(" ", "").ToLower();
                                judul5 = judul5.Replace(" ", "").ToLower();
                                #endregion

                                if (judul == "nomorreferensi" && judul2 == "rekeningdebet" && judul3 == "namapengirim")
                                {
                                    #region Aplikasi Red / Swi - Kliring
                                    int csuccess = 0, cfails = 0;
                                    var rek = file.FileName;
                                    int RekeningId = 0;

                                    var list = new List<object>();
                                    var GetMIs = _con.Query<MI>("SELECT Id, Code FROM MIs");
                                    var GetFunds = _con.Query<Fund>("SELECT Id, Code FROM Funds");

                                    string[] getDate = rek.Replace(" ", String.Empty).Split('-');
                                    DateTime TanggalFund = DateTime.ParseExact(getDate[1].ToLower().Replace(".xls", "").Replace(".xlsx", ""), "ddMMyyyy", CultureInfo.InvariantCulture);

                                    for (int row = 2; row < range_.Rows.Count + 1; row++)
                                    {

                                        int MIId = 0, FundId = 0;

                                        string NoRek = ((_excel.Range)range_.Cells[row, 2]).Text;

                                        if (NoRek == "")
                                            continue;

                                        string noref = ((_excel.Range)range_.Cells[row, 1]).Text;
                                        Int64 payamount = Convert.ToInt64(((_excel.Range)range_.Cells[row, 5]).Value);
                                        string message = ((_excel.Range)range_.Cells[row, 6]).Text;
                                        string receiver_name = ((_excel.Range)range_.Cells[row, 9]).Text;


                                        #region CheckMasterRekening
                                        var resultRek = _con.QueryFirstOrDefault<Rekening>("SELECT Id FROM Rekenings WHERE NoRek = @NoRek", new { NoRek });
                                        if (resultRek == null)
                                        {

                                            var RekId = _con.QuerySingle<int>("INSERT INTO Rekenings (NoRek, CreateDate, UserId, IsDelete) OUTPUT INSERTED.Id VALUES (@NoRek, @DateNow, @UserId, @IsDelete);", new { NoRek = NoRek, DateNow = DateTime.Now, UserId = currentUser.Id, IsDelete = false });

                                            RekeningId = RekId;
                                        }
                                        else
                                        {
                                            RekeningId = resultRek.Id;
                                        }
                                        #endregion

                                        #region CheckMasterMI
                                        var GetMIId = 0;

                                        var GetMICode = "";

                                        foreach (var item in GetMIs)
                                        {
                                            var a = message.IndexOf(item.Code);

                                            if (a != -1)
                                            {
                                                GetMIId = item.Id;
                                                break;
                                            }
                                        }

                                        if (GetMIId == 0)
                                        {
                                            var GetNewMI = message.Substring(5, message.Length);

                                            char[] charMessage = GetNewMI.ToCharArray();

                                            int value = 0, index = 5;

                                            foreach (var item in charMessage)
                                            {
                                                var checkInt = int.TryParse(item.ToString(), out value);
                                                index++;
                                                if (!checkInt)
                                                {
                                                    GetMICode = GetNewMI.Substring(index, 5); break;
                                                }
                                            }

                                            var MI_Id = _con.QuerySingle<int>("INSERT INTO MIs (Code, CreateDate, UserId, IsDelete) OUTPUT INSERTED.Id VALUES (@Code, @DateNow, @UserId, @IsDelete);", new { Code = GetMICode, DateNow = DateTime.Now, UserId = currentUser.Id, IsDelete = false });

                                            MIId = MI_Id;
                                        }
                                        else
                                        {
                                            MIId = GetMIId;
                                        }
                                        #endregion

                                        #region CheckMasterFund
                                        var GetFundId = 0;

                                        var GetFundCode = "";

                                        foreach (var item in GetFunds)
                                        {
                                            var a = message.IndexOf(item.Code);

                                            if (a != -1)
                                            {
                                                GetFundId = item.Id;
                                                break;
                                            }
                                        }

                                        if (GetFundId == 0)
                                        {
                                            var GetNewFund = message.Substring(5, message.Length);

                                            char[] charMessage = GetNewFund.ToCharArray();

                                            int value = 0, index = 0;

                                            foreach (var item in charMessage)
                                            {
                                                var checkInt = int.TryParse(item.ToString(), out value);
                                                index++;
                                                if (!checkInt)

ReksadanaRekon/Views/Redemps/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="row">
    <div class="well">
        <h4>Upload Redemption/Switch Data</h4>
        <div class="form-horizontal">
            <div class="form-group">
                <label class="control-label col-md-2">Browse File</label>
                <div class="col-md-6">
                    <input type="file" multiple="multiple" class="form-control" />
                </div>
            </div>
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <button class="btn btn-primary" id="Upload" data-loading-text="Processing">Upload</button>
                </div>
            </div>
        </div>
    </div>
    <div id="result" class="well">
        <h4>Daftar Hasil Upload</h4>
        <table class="table table-bordered">
            <thead>
                <tr>
                    <th>No</th>
                    <th>Nama File</th>
                    <th>Status Upload</th>
                    <th>Berhasil Terupload</th>
                    <th>Gagal Terupload</th>
                </tr>
            </thead>
            <tbody class="tbody"></tbody>
        </table>
    </div>
    <div class="well text-center">
        <h1>
            <span id="hour">00</span> :
            <span id="min">00</span> :
            <span id="sec">00</span> :
            <span id="milisec">00</span>
        </h1>
    </div>
</div>
<script src="~/Scripts/jquery-1.12.4.js"></script>
<script>
    $(function () {
        $('#result').hide();
    })

    $('#Upload').on('click', function () {
        $("input[type='file']").prop("disabled", true);
        $('#Upload').button('loading');
        reset();
        start();
        $('.tbody').html('');
        $('#result').hide();

        var data = new FormData();

        $.each($("input[type='file']")[0].files, function (i, file) {
            data.append('files', file);
        });

        $.ajax({
            type: 'POST',
            url: '@Url.Action("UploadFiles", "Redemps")',
            cache: false,
            contentType: false,
            processData: false,
            data: data,
            success: function (result) {
                var html = '';
                var no = 1;
                $.each(result.ResultUpload, function (i, value) {
                    html += '<tr>';
                    html += '<td>' + no++ + '</td>';
                    html += '<td>' + value.namafile + '</td>';
                    html += '<td><span class="label label-' + value.warna + '">' + value.status + '</td>';
                    html += '<td>' + value.success + ' data</td>';
                    html += '<td>' + value.fails + ' data</td>';
                    html += '</tr>';
                })

                $('.tbody').append(html);
                $('#result').show();
                stop();
                $("input[type='file']").prop("disabled", false);
                $('#Upload').button('reset');
            },
            error: function (xhr, status, error) {
                stop();
                $("input[type='file']").prop("disabled", false);
                $('#Upload').button('reset');

                var err = JSON.stringify(xhr.responseText.replace(/<[^>]+>/g, '').replaceAll('\r\n', '').trim());
                alert("An error has occured. Error Message: \n\n" + err);
            }
        })
    })


    //=====================Stopwatch=====================//
    function start() {
        x = setInterval(timer, 10);
    } /* Start */

    function stop() {
        clearInterval(x);
    } /* Stop */

    var milisec = 0;
    var sec = 0; /* holds incrementing value */
    var min = 0;
    var hour = 0;

    /* Contains and outputs returned value of  function checkTime */

    var miliSecOut = 0;
    var secOut = 0;
    var minOut = 0;
    var hourOut = 0;

    /* Output variable End */


    function timer() {
        /* Main Timer */


        miliSecOut = checkTime(milisec);
        secOut = checkTime(sec);
        minOut = checkTime(min);
        hourOut = checkTime(hour);

        milisec = ++milisec;

        if (milisec === 100) {
            milisec = 0;
            sec = ++sec;
        }

        if (sec == 60) {
            min = ++min;
            sec = 0;
        }

        if (min == 60) {
            min = 0;
            hour = ++hour;

        }


        document.getElementById("milisec").innerHTML = miliSecOut;
        document.getElementById("sec").innerHTML = secOut;
        document.getElementById("min").innerHTML = minOut;
        document.getElementById("hour").innerHTML = hourOut;

    }


    /* Adds 0 when value is <10 */


    function checkTime(i) {
        if (i < 10) {
            i = "0" + i;
        }
        return i;
    }

    function reset() {


        /*Reset*/

        milisec = 0;
        sec = 0;
        min = 0
        hour = 0;

        document.getElementById("milisec").innerHTML = "00";
        document.getElementById("sec").innerHTML = "00";
        document.getElementById("min").innerHTML = "00";
        document.getElementById("hour").innerHTML = "00";

    }

</script>

ReksadanaRekon/Views/Redemps/Input.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<style>
    .input-sm {
        height: 34px;
    }
</style>

<h3>Input Data Redemption</h3>
<div class="row">
    <div class="well">
        <div class="pull-right">
            <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#myModal" onclick="ClearScreen()">Tambah Data Redemption</button>
        </div>
        <div class="clearfix" style="margin:10px;"></div>
        <table id="table" class="table table-bordered table-hover" style="width:100%">
            <thead>
                <tr>
                    @*<th></th>*@
                    <th>Tgl. Transaksi</th>
                    <th>SA Name</th>
                    <th>Fund Name</th>
                    <th>MI Name</th>
                    <th>Nama Nasabah</th>
                    <th>Nominal</th>
                    <th>Keterangan</th>
                    <th>Status</th>
                    <th>Aksi</th>
                </tr>
            </thead>
        </table>
    </div>
</div>
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true" data-backdrop="static">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">×</button>
                <h4 class="modal-title" id="myModalLabel">Redemption Form</h4>
            </div>
            <div class="modal-body">
                <input type="hidden" class="form-control" id="Id" />
                <div class="form-group col-sm-6">
                    <label for="TglTransaksi">Tgl. Transaksi</label>
                    <input type="date" class="form-control input-sm" id="TglTransaksi" placeholder="Tanggal Transaksi" />
                </div>
                <div class="form-group col-sm-6">
                    <label for="SAs">SA Name</label>
                    <select id="SAs" class="form-control select2" style="width:100%"></select>
                </div>
                <div class="form-group col-sm-6">
                    <label for="Fund">Fund Name</label>
                    <select id="Fund" class="form-control select2" style="width:100%"></select>
                </div>
                <div class="form-group col-sm-6">
                    <label for="MIs">MI Name</label>
                    <select id="MIs" class="form-control select2" style="width:100%;"></select>
                </div>
                <div class="form-group col-sm-6">
                    <label for="NamaNasabah">Nama Nasabah</label>
                    <input type="text" oninput="this.value = this.value.toUpperCase()" class="form-control input-sm" id="NamaNasabah" placeholder="Nama Nasabah" />
                </div>
                <div class="form-group col-sm-6">
                    <label for="Nominal">Nominal</label>
                    <input type="text" class="form-control input-sm" id="Nominal" placeholder="Nominal" value="0" oninput="this.value = this.value.replace(/[^0-9]/g, '');" onclick="this.setSelectionRange(0, this.value.length)" />
                </div>
                <div class="form-group col-sm-6">
                    <label for="Nominal">Keterangan</label>
                    <textarea type="text" class="form-control input-sm" id="KeteranganRetur" placeholder="Keterangan Retur"></textarea>
                </div>
                <div class="clearfix"></div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-primary" id="Save" onclick="Save();">Simpan</button>
                <button type="button" class="btn btn-primary" id="Update" style="display:none;" onclick="Edit();">Update</button>
                <button type="button" class="btn btn-default" data-dismiss="modal" onclick="ClearScreen()" ;>Close</button>
            </div>
        </div>
    </div>
</div>

<script src="~/Content/sweetalert/sweetalert.min.js"></script>
<script src="~/Scripts/jquery-1.12.4.js"></script>
<link href="~/Content/sweetalert/sweetalert.css" rel="stylesheet" />
<script>
    $(document).ready(function () {
        $.fn.modal.Constructor.prototype.enforceFocus = function () { };

        $('.select2').select2({
            theme: "bootstrap",
            dropdownAutoWidth: true

        });

        LoadSACombo();
        LoadMICombo();
        LoadFundCombo();
        ClearScreen();

        var table = $('#table').DataTable({
            "scrollX": true,
            "ajax": {
                "url": "@Url.Action("GetList", "Redemps")",
                "type": "POST",
                "datatype": "json"
            },
            "columns": [
                    //{ "data": "Id", "name": "Id", "autoWidth": true }, //index 0
                    { "data": "TransDate", "name": "TransDate", "autoWidth": true, "render": function (d) { return moment(d).format('DD/MM/YY') } }, //index 1
                    {
                        "data": "SA", "name": "SA", "autoWidth": true,
                        "render": function (d) {
                            if (d == null) {
                                return "-";
                            } else {
                                return d;
                            }
                        }
                    },               //index 4
                    {
                        "data": "Fund", "name": "Fund", "autoWidth": true,
                        "render": function (d) {
                            return d.substr(11, d.length)
                        }
                    },   //index 5
                    { "data": "MI", "name": "MI", "autoWidth": true },   //index 6
                    { "data": "NamaNasabah", "name": "NamaNasabah", "autoWidth": true },   //index 8
                    { "data": "Nominal", "name": "Nominal", "autoWidth": true, "render": $.fn.dataTable.render.number('.', '', 0, '') },   //index 9
                    { "data": "KeteranganRetur", "name": "KeteranganRetur", "autoWidth": true },   //index 8
                    {
                        "data": "MatchingNama", "name": "MatchingNama", "autoWidth": true,
                        "render": function (data, type, row) {
                            return "<span class='label label-xs label-" + row.MatchingWarna + "'>" + row.MatchingNama + "</span>"
                        }
                    },   //index 10
                    {
                        "autoWidth": true,
                        "render": function (data, type, row) {
                            return "<button class='btn btn-success btn-xs' onclick='GetById(" + row.Id + ")'>Edit</button> <button class='btn btn-danger btn-xs' onclick='Delete(" + row.Id + ")'>Delete</button>"
                        }
                    }
            ],
            'columnDefs': [
              //{
              //    'targets': 0,
              //    'checkboxes': {
              //        'selectRow': true
              //    }
              //},
              {
                  'targets': 1,
                  'render': $.fn.dataTable.render.ellipsis(15)
              }
            ]
        });
    })

    function GetById(id) {
        $.ajax({
            url: "@Url.Action("GetById", "Redemps")/" + id,
            type: "GET",
            dataType: "json",
            success: function (result) {
                $('#Id').val(result.Id);
                $('#TglTransaksi').val(formatDate(result.TransDate));
                $('#NamaNasabah').val(result.Nasabah);
                $('#SAs').val(result.SAId).trigger('change');
                $('#Fund').val(result.FundId).trigger('change');
                $('#MIs').val(result.MIId).trigger('change');
                $('#Nominal').val(result.Nominal);
                $('#KeteranganRetur').val(result.KeteranganRetur);



                $('#myModal').modal('show');
                $('#Update').show();
                $('#Save').hide();
            }
        })
    }

    function LoadSACombo() {
        $.ajax({
            url: '@Url.Action("GetSA", "Redemps")/',
            type: 'GET',
            dataType: 'json',
            success: function (result) {
                var sa = $('#SAs');
                $("<option></option>").val(null).text("-- Pilih SA --").appendTo(sa);
                $.each(result, function (i, sell) {
                    $("<option></option>").val(sell.Id).text(sell.Nama).appendTo(sa);
                });
            }
        });
    }

    function LoadFundCombo() {
        $.ajax({
            url: '@Url.Action("GetFund", "Redemps")/',
            type: 'GET',
            dataType: 'json',
            success: function (result) {
                var fu = $('#Fund');
                $("<option></option>").val(null).text("-- Pilih Fund --").appendTo(fu);
                $.each(result, function (i, fund) {
                    $("<option></option>").val(fund.Id).text(fund.Nama).appendTo(fu);
                });
            }
        });
    }

    function LoadMICombo() {
        $.ajax({
            url: '@Url.Action("GetMI", "Redemps")/',
            type: 'GET',
            dataType: 'json',
            success: function (result) {
                var mi = $('#MIs');
                $("<option></option>").val(null).text("-- Pilih MI --").appendTo(mi);
                $.each(result, function (i, mis) {
                    $("<option></option>").val(mis.Id).text(mis.Nama).appendTo(mi);
                });
            }
        });
    }

    function LoadBankCombo() {
        $.ajax({
            url: '@Url.Action("GetBank", "Redemps")/',
            type: 'GET',
            dataType: 'json',
            success: function (result) {
                var bank = $('#Bank');
                $("<option></option>").val(null).text("-- Pilih Bank --").appendTo(bank);
                $.each(result, function (i, value) {
                    $("<option></option>").val(value.Id).text(value.Nama).appendTo(bank);
                });
            }
        });
    }



    function Save() {
        var data = new Object();
        data.TransDate = $('#TglTransaksi').val();
        data.Nasabah = $('#NamaNasabah').val();
        data.SAId = $('#SAs').val();
        data.FundId = $('#Fund').val();
        data.MIId = $('#MIs').val();
        data.Nominal = $('#Nominal').val();
        data.KeteranganUser = $('#KeteranganUser').val();
        $.ajax({
            url: "@Url.Action("Save", "Redemps")",
            type: 'POST',
            dataType: 'json',
            data: data,
            success: function (result) {
                swal({
                    title: "Saved!",
                    text: "That data has been saved!",
                    type: "success",
                    timer: 1000
                });

                $('#table').DataTable().ajax.reload();
                $('#myModal').modal('hide');
            }
        });

        console.table(data)
    }

    function Edit() {
        var data = new Object();
        data.Id = $('#Id').val();
        data.TransDate = $('#TglTransaksi').val();
        data.Nasabah = $('#NamaNasabah').val();
        data.SAId = $('#SAs').val();
        data.FundId = $('#Fund').val();
        data.MIId = $('#MIs').val();
        data.Nominal = $('#Nominal').val();
        data.KeteranganUser = $('#KeteranganUser').val();
        $.ajax({
            url: "@Url.Action("Save", "Redemps")",
            data: data,
            type: "POST",
            dataType: "json",
            success: function (result) {
                swal({
                    title: "Saved!",
                    text: "That data has been saved!",
                    type: "success",
                    timer: 1000
                });

                $('#table').DataTable().ajax.reload();
                ClearScreen();
                $('#myModal').modal('hide');
            }
        });
    }

    function Delete(id) {
        swal({
            title: "Are you sure?",
            text: "You will not be able to recover this imaginary file!",
            type: "warning",
            showCancelButton: true,
            confirmButtonColor: "#DD6B55",
            confirmButtonText: "Yes, delete it!",
            closeOnConfirm: false
        }, function () {
            $.ajax({
                url: "@Url.Action("Delete", "Redemps")/" + id,
                type: "POST",
                success: function (response) {
                    swal({
                        title: "Deleted!",
                        text: "That data has been delete!",
                        type: "success",
                        timer: 1000
                    });

                    $('#table').DataTable().ajax.reload();
                },
                error: function (response) {
                    swal("Oops", "We couldn't connect to the server!", "error");
                }
            });
        });
    }

    function formatDate(dates) {
        date = new Date(parseInt(dates.substr(6)));
        var year = date.getFullYear();
        var month = (1 + date.getMonth()).toString();
        month = month.length > 1 ? month : '0' + month;
        var day = date.getDate().toString();
        day = day.length > 1 ? day : '0' + day;

        return year + '-' + month + '-' + day;
    }

    function ClearScreen() {
        $('#Update').hide();
        $('#Save').show();
        $('#Id').val('');
        $('#TglTransaksi').val('');
        $('#NamaNasabah').val('');
        $('#SAs option').eq(0).prop('selected', true).trigger('change');
        $('#Fund option').eq(0).prop('selected', true).trigger('change');
        $('#MIs option').eq(0).prop('selected', true).trigger('change');
        $('#Nominal').val('0');
        $('#KeteranganRetur').val('');
    }
</script>